import React,{useMemo,useState} from 'react';
import {UploadCloud,FileText,CheckCircle2,AlertCircle,RefreshCw} from 'lucide-react';
import SectionHeader from '../components/SectionHeader';

const normalize=(v='')=>String(v).trim().toLowerCase().replace(/[^a-z0-9]/g,'');
const splitCsv=(line)=>{const out=[];let cur='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){quoted=!quoted}else if(c===','&&!quoted){out.push(cur.trim());cur=''}else cur+=c}out.push(cur.trim());return out};
const parseCsv=(text,platform)=>{
 const lines=text.split(/\r?\n/).filter(Boolean); if(lines.length<2)return [];
 const headers=splitCsv(lines[0]).map(normalize);
 const find=(names)=>{const i=headers.findIndex(h=>names.includes(h));return i};
 const dateI=find(['date','transactiondate','tradedate','orderdate']); const platformI=find(['platform','source']); const assetI=find(['symbol','asset','ticker','stock']); const typeI=find(['transactiontype','type','action','tradetype']); const qtyI=find(['quantity','qty','units']); const priceI=find(['price','averageprice','avgprice','rate']); const totalI=find(['totalamount','amount','value','total']); const currencyI=find(['currency']);
 return lines.slice(1).map((line,idx)=>{const c=splitCsv(line); const type=(c[typeI>=0?typeI:0]||'BUY').toUpperCase(); const qty=Number(c[qtyI>=0?qtyI:0])||0; const price=Number(c[priceI>=0?priceI:0])||0; const total=Number(c[totalI>=0?totalI:0])||qty*price; const date=c[dateI>=0?dateI:0]||new Date().toISOString().slice(0,10); const asset=c[assetI>=0?assetI:1]||`ASSET-${idx+1}`; const rowPlatform=platformI>=0?(c[platformI]||platform):platform; const currency=currencyI>=0?(c[currencyI]||'INR'):'INR'; return {id:`IMP-${Date.now()}-${idx}`,date,platform:rowPlatform,asset:asset.toUpperCase(),type:type==='SELL'?'SELL':'BUY',qty,price,total,status:'Imported',currency};});
};
const key=t=>[t.platform,t.date,t.asset,t.type,t.qty,t.price,t.total,t.currency||'INR'].map(normalize).join('|');

export default function Imports({transactions,setTransactions,holdings,setHoldings}){
 const [platform,setPlatform]=useState('Groww'); const [file,setFile]=useState(null); const [rows,setRows]=useState([]); const [done,setDone]=useState(null); const [error,setError]=useState('');
 const existingKeys=useMemo(()=>new Set(transactions.map(key)),[transactions]);
 const newRows=rows.filter(r=>!existingKeys.has(key(r))); const duplicateRows=rows.filter(r=>existingKeys.has(key(r)));
 const handle=async e=>{const f=e.target.files?.[0];if(!f)return;setFile(f);setDone(null);setError('');setRows([]); if(!f.name.toLowerCase().endsWith('.csv')){setError('CSV preview is supported in this frontend demo. Excel/PDF parsing will be handled by the Spring Boot backend.');return;} try{const text=await f.text();const parsed=parseCsv(text,platform);if(!parsed.length)throw new Error('No transactions found.');setRows(parsed)}catch(err){setError(err.message||'Could not parse this statement.')}};
 const importNew=()=>{if(!newRows.length)return; const imported=[...transactions,...newRows]; setTransactions(imported); let next=[...holdings]; newRows.forEach(t=>{const i=next.findIndex(h=>h.symbol===t.asset && h.platform===t.platform); const signed=t.type==='SELL'?-1:1; if(i>=0){const h={...next[i]};const oldQty=Number(h.qty)||0;const oldAvg=Number(h.avg)||0;const q=Number(t.qty)||0;const px=Number(t.price)||0;const newQty=Math.max(0,oldQty+signed*q); if(t.type==='BUY' && newQty>0) h.avg=((oldQty*oldAvg)+(q*px))/newQty; h.qty=newQty; h.invested=Math.max(0,(Number(h.invested)||0)+(signed*q*px)); next[i]=h;} else if(t.type==='BUY'){next.push({id:Date.now()+Math.random(),name:t.asset,symbol:t.asset,type:'Investment',platform:t.platform,qty:t.qty,avg:t.price,current:t.price,invested:t.total,category:'Imported',currency:t.currency||'INR'});}});setHoldings(next);setRows([]);setFile(null);setDone({added:newRows.length,duplicates:duplicateRows.length});};
 return <><SectionHeader eyebrow="DATA IMPORT" title="Import Statements" description="Bring transactions from your investment platforms into one monitoring system."/><div className="grid-2 import-grid"><div className="card import-card"><div className="upload-icon"><UploadCloud size={25}/></div><h3>Upload a statement</h3><p className="muted">Upload a new or updated CSV statement. PortfolioX compares it with existing transactions before importing.</p><label>Source platform<select value={platform} onChange={e=>setPlatform(e.target.value)}><option>Groww</option><option>INDmoney</option><option>CoinSwitch</option><option>Zerodha</option><option>Upstox</option><option>Other</option></select></label><label className="dropzone"><input type="file" accept=".csv,.xlsx,.xls,.pdf" onChange={handle}/><FileText size={22}/><strong>{file?file.name:'Choose a statement file'}</strong><span>CSV preview supported · Excel/PDF backend parsing later</span></label><button className="primary full" disabled={!newRows.length} onClick={importNew}>{newRows.length?`Import ${newRows.length} new transaction${newRows.length>1?'s':''}`:'Upload a CSV to preview'}</button>{error&&<div className="notice"><AlertCircle size={17}/><span>{error}</span></div>}{done&&<div className="success-box"><CheckCircle2 size={18}/><span>Imported <b>{done.added}</b> new transaction(s). Skipped <b>{done.duplicates}</b> duplicate(s).</span></div>}</div><div className="card import-card"><h3>Import preview</h3>{rows.length?<><div className="import-summary"><div><strong>{newRows.length}</strong><span>New</span></div><div><strong>{duplicateRows.length}</strong><span>Duplicates</span></div><div><strong>{rows.length}</strong><span>Total rows</span></div></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Platform</th><th>Asset</th><th>Type</th><th>Qty</th><th>Price</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.date}</td><td>{r.platform}</td><td><strong>{r.asset}</strong></td><td>{r.type}</td><td>{r.qty}</td><td>{r.price}</td><td><span className={existingKeys.has(key(r))?'status duplicate-status':'status'}>{existingKeys.has(key(r))?'Duplicate':'New'}</span></td></tr>)}</tbody></table></div><button className="secondary full" onClick={()=>{setRows([]);setFile(null)}}><RefreshCw size={14}/> Clear preview</button></>:<div className="empty-preview"><FileText size={24}/><strong>No statement loaded</strong><span className="muted">Upload a CSV to see which transactions are new and which already exist.</span></div>}<div className="notice"><AlertCircle size={17}/><span>Updated statements are safe to upload again: matching transactions are detected and are not added twice.</span></div></div></div></>;
}
